### ISSUE TITLE
Suggestion: Add github public template button

### ISSUE THREAD

**Issue by BenTechCoder** [madrilene/eleventy-excellent#1]
Hiya @madrilene! Love what you've done with the original [buildexcellentwebsit.es](buildexcellentwebsit.es) 

I'm going to clone it to experiment with the tailwind workflow but a quick suggestionn might be to toggle the public template checkmark in the repository settings. As seen in this screenshot from my own starter [space otterty](space-otterty.netlify.app) 

 
![image](https://user-images.githubusercontent.com/71533854/198907802-7817bc4d-8d94-4701-8616-bad2c8a506fb.png)

Just a suggestion 👍

Thanks for the starter!

Best, Ben

**Comment by madrilene** [comment]
Done! Thank you!
