### ISSUE TITLE
Remove Minification

### ISSUE THREAD

**Issue by flamedfury** [madrilene/eleventy-excellent#13]
Hello @madrilene :wave: 

What steps can I take to remove the HTML/CSS minification? 

The communities that I am in love to view source and look at how websites are constructed, and I would love not to obscure the structure of my website. 

Is this as straight forward as removing the various npm packages?

Let me know ~fLaMEd

**Comment by madrilene** [comment]
Hi, sure! 

Just comment out the HTML transfom in the config file: https://github.com/madrilene/eleventy-excellent/blob/main/.eleventy.js#L97

And get rid of cssnano: https://github.com/madrilene/eleventy-excellent/blob/main/config/template-languages/css-config.js#L26

**Comment by flamedfury** [comment]
All done, thanks heaps :)
