### ISSUE TITLE
Fantastic (EXCELLENT!) template! Looking for TAGS support for post

### ISSUE THREAD

**Issue by skopanev** [madrilene/eleventy-excellent#17]
### Hi! Thanks for this template! Looks amazing!

It would be awesome to tag posts and sort them by tags! Thx in advance!

**Comment by madrilene** [comment]
Hello! :) For the time being I would rather not push the starter further in one direction (and tags would do that in my opinion). It should provide a basis for development in any direction, not just as a classic blog. That said, it is quite easy to expand this base in the direction of tags. Zack Leatherman has written a quick tip for this in the docs: https://www.11ty.dev/docs/quicktips/tag-pages/

**Comment by flamedfury** [comment]
@skopanev check out [this commit](https://github.com/flamedfury/flamedfury.com/commit/2db3f80a5029938ac4791697cc2f303b6943a3e8) where I implemented zero maintenance tags into my eleventy-excellent based project.

**Comment by madrilene** [comment]
I created a demo in a separate branch: https://github.com/madrilene/eleventy-excellent/tree/demo-tags
Preview: https://eleventy-excellent-tags.netlify.app/tags/
