### ISSUE TITLE
sitemap.xml generated urls from src/assets css and js

### ISSUE THREAD

**Issue by DanyJack** [madrilene/eleventy-excellent#20]
Hi, thank you for you fantastic job!

The sitemap generated has the right page and post URLs but also all the links from the src/assets CSS and JS.

 "version": "1.5.4"

Thank you for your check.

**Comment by madrilene** [comment]
You're right, I fixex that, thank you! 
https://github.com/madrilene/eleventy-excellent/commit/ab9df8fa777450a8a6b57f3729eed3270343a6a5
