### ISSUE TITLE
Post Tags on Blog Cards

### ISSUE THREAD

**Issue by flamedfury** [madrilene/eleventy-excellent#40]
Hey again :wave: 

Throwing it out there if you might know why the blog cards is just rendering `posts` as the tag rather than the tags defined in each posts front matter? 

Have I configured something somewhere to cause this?

See post grid on [main page](https://flamedfury.com)  and the [posts page](https://flamedfury.com/posts/)

**Comment by madrilene** [comment]
Hi! This code sets to only show the second item in the array, as the first is always "posts".

```
    if
          activateTags and item.data.tags.length > 1
        %}
          <span class="button post-tag"> {{ item.data.tags[1] }} </span>
        {% endif %}
```

For some reason, you get posts twice: 

![image](https://github.com/madrilene/eleventy-excellent/assets/62096871/040464eb-16a5-4d96-a601-911fa9e66c95)

in `posts.json` you can remove `"tags": "posts",` and it should work again. 

{
  "layout": "post",
  "permalink": "/blog/{{ title | slugify }}/index.html"
}

Will look into making this more reliable.

**Comment by flamedfury** [comment]
Thank you 🎉
