### ISSUE TITLE
Dark theme custom colors don't render.

### ISSUE THREAD

**Issue by Midknight** [madrilene/eleventy-excellent#41]
While working with this template I found that iOS Safari or Firefox do not render the custom color variables while in the dark theme appropriately. I have looked on the demo site as it also shows this issue. I am trying to track down what might be causing it but thought to bring it up.

Screenshot of iPhone with Firefox iOS.

![iPhone-FirefoxiOS](https://github.com/madrilene/eleventy-excellent/assets/274881/9afa283c-fa5d-4f8c-8e07-1298fc47f622)

**Comment by madrilene** [comment]
Hi, thanks!
I tend to skip testing that system. 
Should be fixed now for Safari / iOS (so, also for Firefox and Chrome).

https://github.com/madrilene/eleventy-excellent/blob/main/src/assets/css/global/variables.css

**Comment by Midknight** [comment]
Thank you! Ok I see now what you were pushing for with HSL ([types: <color>: hsl() (HSL color model): Mix <percentage> and <number> in parameters](https://caniuse.com/mdn-css_types_color_hsl_mixed_type_parameters)

Was missing that as I was like there shouldn't be any issues here.
