### ISSUE TITLE
Partial -> Meta-info.njk (Description and Personal.Platforms Corrections)

### ISSUE THREAD

**Issue by Midknight** [madrilene/eleventy-excellent#45]
Hi Lene,
You will need to update your meta description as there is an error in the elseif. States elif instead of elseif.

Also your Mastodon link states personal.social where it should be personal.platforms.

Also in your theme-switch.css you will need to add the following to ensure outline.

.theme-switch .button[aria-pressed='false']:focus-visible {
    outline: 3px solid var(--color-base-light);
    outline-offset: 0.3ch;
  }

Thanks!

**Comment by madrilene** [comment]
Fixed here: https://github.com/madrilene/eleventy-excellent/commit/152e9ee2c7174267722b522752d5139b1bfc9e00

For `.theme-switch .button[aria-pressed='true']` I added `outline-color: var(--_color-primary-contrast);`. 

I left `elif` as is, as this is valid Nunjucks syntax: https://mozilla.github.io/nunjucks/templating.html#tags

Thank you for pointing out the bugs!
