### ISSUE TITLE
adding a license?

### ISSUE THREAD

**Issue by jeromedockes** [madrilene/eleventy-excellent#5]
Hello @madrilene , thank you so much for creating and sharing this beautiful 11ty starter! And also for the resources you share in the README.

To know under what conditions this starter can be reused, I was wondering if you could add a LICENSE to the repository? Sorry if there is already one and I missed it

**Comment by madrilene** [comment]
I had an ISC license in the package.json, but it was a little hard to see. I have now placed it further up and also added LICENSE.md. Please use the starter as you like, I would be delighted to receive a link to a finished project, so I can add it to the "built with" section"!

**Comment by jeromedockes** [comment]
Thank you very much, and sorry for missing the license in the package.json! when/if I put a finished project online I'll make sure to send you the link
