### ISSUE TITLE
Adding an image to home.njk

### ISSUE THREAD

**Issue by ioalexei** [madrilene/eleventy-excellent#58]
I've cloned the repo and am playing around with the templates - but Im having trouble getting an image to display on the home page through index.njk.

I've added a line: 
`{% image "./src/assets/images/index_image.jpg", "", "" %}`

but when I run `npm start` I get an error: 
```
[11ty] Problem writing Eleventy templates:
[11ty] 1. Having trouble rendering njk template ./src/pages/index.njk (via TemplateContentRenderError)
[11ty] 2. ENOENT: no such file or directory, stat './src/assets/images/index_image.jpg'
```

This is a very basic question but how would I get an image to show up?

**Comment by madrilene** [comment]
Hi Alexei,

are you sure the image is present in this path?

./src/assets/images/index_image.jpg

If you give me access / the link to your repo I can look into this.

**Comment by ioalexei** [comment]
Thank you! 

Here's the link: 
https://github.com/ioalexei/11ty-excellent-index-maps-xyz

( I generalised the name of the image but the actual image I'm trying to add is `contours.jpg`

I'm sure I'm missing something very obvious but any help would be very appreciated!

**Comment by madrilene** [comment]
This was not your issue, but looking into this I saw that the OG images script terminates the dev server if no OG images directory exists (you have no posts). I fixed this here: https://github.com/madrilene/eleventy-excellent/commit/d3630aa5633f5af457f7c0497f8f5f7a0a9c7434

As for your issue, I'm not completely sure why, but it seems it has to do with your images. I tried with another and it works fine, and I ran countours.jpg through https://squoosh.app/ and it then also worked fine. Let me know if you find out what causes the images not to be recognized by Eleventy - may have something to do with how you exported them?

Also, when you don't pass any other arguments, you may just write 

`{% image "./src/assets/images/countours.jpg" %}`

This sets the empty alt attribute by default.

**Comment by ioalexei** [comment]
Just tried with another image and it also worked (I should have tried this first...) so clearly something to do with my contours image. Will look into it and let you know if I find the answer. 

Thanks so much for looking into it!
