### ISSUE TITLE
[QUESTION] TailwindCSS config file copy

### ISSUE THREAD

**Issue by juchom** [madrilene/eleventy-excellent#61]
Hello,

First thing first, thanks for this great repo and its documentation !

I have one question about this piece of code in the `css-config.js`.

https://github.com/madrilene/eleventy-excellent/blob/acd28bc567dcce293c3a15037056979491e6c2bc/src/_config/plugins/css-config.js#L15-L28

I don't understand why you are copying some files to `dist/assets/css/` some others to `src/_includes/css/` and to both directories.

What is the logic behind this ?

And I also got lost here, with this last lines in `css-inline.njk`

https://github.com/madrilene/eleventy-excellent/blob/acd28bc567dcce293c3a15037056979491e6c2bc/src/_includes/head/css-inline.njk#L10-L13

Thanks for your help

**Comment by madrilene** [comment]
You are right! That was a remnant of another approach, and I've just cleaned that up. 
https://github.com/madrilene/eleventy-excellent/commit/080f490a9d9b345b0cf4323dcf7958bf9c54d6bd

As for the other question, the starter works with the idea that there are styles that apply globally to all, or are used so often on different pages that they are available globally. This "global" CSS collection is loaded on every page, and added to the global bundle here:

`{% css “global” %}{% include “css/global.css” %}{% endcss %}`

The Eleventy plugin https://github.com/11ty/eleventy-plugin-bundle is used for this.

All styles that should be globally available must be placed in this layer: `src/assets/css/global`

If you want to know how best to sort them here, the CSS methodology is https://cube.fyi/. 

Then there are styles that are only used once or twice, or in any case selectively, and you can include these on a partial or template level. To do this, they must be stored here: `src/assets/css/bundle`

I usually name them here by their purpos (`table.css` for table styles) or by template they are used for (`post.css`). You must actively include these where you need them, so they get added to the "inline" bundle (a better name for the bundle migth be something like "selective"). The template `styleguide.njk`, for example, includes these two style collections:

```
{%- css “inline” -%}
  {%- include 'css/styleguide.css' -%}
  {%- include 'css/table.css' -%}
{%- endcss -%}
```

Finally, there is a component layer, but I don't use it consistently in the starter for CSS. In fact, I just changed the approach here in the last commit, and also include the custom-card styles as an inline bundle. The idea, however, is that style collections stored here are included by _webC_, which integrates them directly from the output folder. In principle, _webC_ should also integrate them inline, but this only seems to work in projects that use _webC_ as a template language. In any case, I haven't got it to work yet. 

`<link rel=“stylesheet” href=“/assets/css/components/custom-card.css” />`

At the moment the folder is empty, but I'm keeping the logic for it for now. 

`src/assets/scripts` works similarly, by the way.

**Comment by juchom** [comment]
Ok, thanks for the clarification and again thanks for this repo !
