### ISSUE TITLE
Missing /index.html in sitemap.xml

### ISSUE THREAD

**Issue by juchom** [madrilene/eleventy-excellent#62]
Hello Lene,

I think that there is an issue here : 

https://github.com/madrilene/eleventy-excellent/blob/3f56328f4d461f52021ba294535a313f46d48a9f/src/_config/collections.js#L6-L9

With this glob you are missing the `index.njk` at the root of the `pages` directory, and you are missing it in the `sitemap.xml`

I've done it like this on my site

```js
/** All markdown files as a collection for sitemap.xml */ 
 export const onlyMarkdown = collection => { 
   return collection.getFilteredByGlob('./src/**/*.{md,njk}'); 
 }; 
```

**Comment by madrilene** [comment]
totally! Big oversight. Fixed here: https://github.com/madrilene/eleventy-excellent/commit/4fca7b9d1837b5607ba8c353e3d097bc9d18375b
